language: python
python: 3.7
dist: xenial
sudo: true

install:
  - pip install -e .[test]
script:
  - py.test --doctest-modules --pep8 standardcitations -v --cov standardcitations --cov-report term-missing
after_success:
  - coveralls

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  skip_existing: true
  on:
    tags: true
