language: python
python:
  - "2.7"
install:
  - pip install -e .
before_script:
  - pip install -r requirements.txt
script:
  - py.test --doctest-modules --pep8 standardcitations -v --cov standardcitations --cov-report term-missing
after_success:
  - coveralls

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  skip_existing: true
  on:
    tags: true
