language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
dist: xenial
sudo: true

install:
  - pip install -e .[test]
script:
  - make test
after_success:
  - coveralls

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  skip_existing: true
  on:
    tags: true
